In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x=df.drop('species',axis=1)
y=df['species']

In [7]:
x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [10]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [11]:
model_knn.score(x_train,y_train)

0.9666666666666667

In [12]:
from sklearn.svm import SVC

In [13]:
model_svm = SVC(gamma='auto') #c=punishment

In [14]:
model_svm.fit(x_train,y_train)

SVC(gamma='auto')

In [15]:
model_svm.score(x_train,y_train)

0.9916666666666667

In [16]:
#now lets use the grid search CV
from sklearn.model_selection import GridSearchCV

In [17]:
classifier = GridSearchCV((model_svm),{
    'C':[1,20,30],
    'kernel':['linear','rbf']
},cv=5,return_train_score=False)

In [18]:
#not need to do train test split in cross validation
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 20, 30], 'kernel': ['linear', 'rbf']})

In [19]:
classifier.fit(x,y)
classifier.cv_results_

{'mean_fit_time': array([0.00849538, 0.00573421, 0.00567436, 0.01157737, 0.00397706,
        0.0061388 ]),
 'std_fit_time': array([0.00724639, 0.00222417, 0.00226736, 0.00415763, 0.00014433,
        0.00286398]),
 'mean_score_time': array([0.00513506, 0.00452747, 0.00394197, 0.00817742, 0.00308065,
        0.00618858]),
 'std_score_time': array([0.00267064, 0.00178389, 0.00145056, 0.00381542, 0.00018663,
        0.00329298]),
 'param_C': masked_array(data=[1, 1, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.9       ,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.96666667, 0.96666667, 0.96      ,
        0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.0421637 , 0.03651484, 0.04898979,
        0.03887301]),
 'rank_test_score': array([1, 1, 4, 3, 5, 5], dtype=int32)}

In [20]:
results=pd.DataFrame(classifier.cv_results_)

In [21]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008495,0.007246,0.005135,0.002671,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005734,0.002224,0.004527,0.001784,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005674,0.002267,0.003942,0.001451,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
3,0.011577,0.004158,0.008177,0.003815,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
4,0.003977,0.000144,0.003081,0.000187,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5
5,0.006139,0.002864,0.006189,0.003293,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5

In [23]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       20       linear         0.966667
3       20          rbf         0.966667
4       30       linear         0.960000
5       30          rbf         0.960000

In [24]:
#Random Search CV
from sklearn.model_selection import RandomizedSearchCV

In [25]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},n_iter=4,cv=5,return_train_score=False)

In [26]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [27]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00429611, 0.00451159, 0.00396404, 0.00416684]),
 'std_fit_time': array([3.41293624e-04, 9.07043573e-04, 7.43891337e-05, 5.19375380e-04]),
 'mean_score_time': array([0.00318465, 0.00314665, 0.00299506, 0.00292115]),
 'std_score_time': array([2.51877132e-04, 1.76407516e-04, 8.88714200e-05, 1.07335123e-04]),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'linear', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[20, 10, 10, 1],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      , 0.97333333, 0.98      ]),
 'std_test_score': array([0.03651484, 0.01632993, 0.03887301, 0.01632993]),
 'rank_test_score': array([4, 1, 3, 1], dtype=int32)}

In [29]:
results_r=pd.DataFrame(classifier_r.cv_results_)

In [30]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008495,0.007246,0.005135,0.002671,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005734,0.002224,0.004527,0.001784,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005674,0.002267,0.003942,0.001451,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
3,0.011577,0.004158,0.008177,0.003815,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
4,0.003977,0.000144,0.003081,0.000187,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5
5,0.006139,0.002864,0.006189,0.003293,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5

In [31]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1       10          rbf         0.980000
2       10       linear         0.973333
3        1       linear         0.980000