In [1]:
#transform
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset('taxis')

In [3]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [5]:
df.groupby(by='pickup_borough')['fare'].transform('mean')

0       11.152889
1       11.152889
2       11.152889
3       11.152889
4       11.152889
          ...
6428    11.152889
6429    24.934642
6430    16.520836
6431    16.520836
6432    16.520836
Name: fare, Length: 6433, dtype: float64

In [6]:
df['avg_fare']=df.groupby(by='pickup_borough')['fare'].transform('mean')

In [7]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,avg_fare
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,11.152889
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,11.152889
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,11.152889
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,11.152889
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,11.152889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan,11.152889
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx,24.934642
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn,16.520836
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn,16.520836
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn,16.520836

In [9]:
df[['pickup_borough','fare','avg_fare']]

     pickup_borough  fare   avg_fare
0         Manhattan   7.0  11.152889
1         Manhattan   5.0  11.152889
2         Manhattan   7.5  11.152889
3         Manhattan  27.0  11.152889
4         Manhattan   9.0  11.152889
...             ...   ...        ...
6428      Manhattan   4.5  11.152889
6429         Queens  58.0  24.934642
6430       Brooklyn  16.0  16.520836
6431       Brooklyn   6.0  16.520836
6432       Brooklyn  15.0  16.520836

[6433 rows x 3 columns]

In [10]:
#filter

In [11]:
#['fare'] in series
#[['fare']] in data frame

In [15]:
df.groupby(by='pickup_borough')[['fare']].mean()

                     fare
pickup_borough
Bronx           20.999091
Brooklyn        16.520836
Manhattan       11.152889
Queens          24.934642

In [20]:
df.groupby(by='pickup_borough')[['fare']].filter(lambda x: x['fare'].mean() > 20)

      fare
10    17.0
22    31.5
43    28.0
53    36.0
56    52.0
...    ...
6417  35.0
6418   7.5
6423  18.5
6427  20.0
6429  58.0

[756 rows x 1 columns]

In [24]:
df.groupby(['color','payment']).filter(lambda x : x['tip'].max()>25)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,avg_fare
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,11.152889
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,11.152889
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,11.152889
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,11.152889
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan,11.152889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5446,2019-03-11 21:19:42,2019-03-11 21:29:23,1,2.09,9.5,2.66,0.0,15.96,yellow,credit card,Battery Park City,Financial District North,Manhattan,Manhattan,11.152889
5447,2019-03-20 18:09:46,2019-03-20 18:16:52,1,1.52,7.5,2.36,0.0,14.16,yellow,credit card,Upper West Side South,Upper East Side North,Manhattan,Manhattan,11.152889
5448,2019-03-09 11:08:09,2019-03-09 11:18:03,1,2.05,9.5,2.56,0.0,15.36,yellow,credit card,Lenox Hill West,Upper West Side South,Manhattan,Manhattan,11.152889
5449,2019-03-22 18:12:50,2019-03-22 18:22:05,1,1.07,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Penn Station/Madison Sq West,Manhattan,Manhattan,11.152889
5450,2019-03-07 18:02:33,2019-03-07 18:13:32,1,1.80,9.0,1.33,0.0,14.63,yellow,credit card,Lincoln Square East,Upper West Side North,Manhattan,Manhattan,11.152889

In [26]:
df.groupby(['color','payment'])[['tip']].max()

                      tip
color  payment
green  cash          0.00
       credit card  10.71
yellow cash          0.00
       credit card  33.20