In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('D:/90 days AI Ml/Day 10 pandas/messy_sales_data.csv')
df

,Order_ID,Customer Name,email,Phone Number,Region,country,Product,Qty,unit price,Discount,Total,Order Date,Status,payment,Sales_Rep
0,1001,Alice Johnson,alice.johnson@email.com,555-0101,North America,USA,Wireless Headphones,2,89.99,10%,161.98,01/05/2024,Delivered,Credit Card,Mike T.
1,1002,BOB SMITH,bob.smith@email.com,+1-555-0102,north america,Canada,Winter Jacket,1,149.99,NaN,149.99,2024-01-07,delivered,paypal,Sarah K.
2,1003,Clara Lee,CLARA.LEE@EMAIL.COM,(44) 20-5550103,Europe,UK,Coffee Maker,1,59.99,5%,57.00,10-Jan-2024,DELIVERED,Debit Card,James R.
3,1004,david muller,david.muller@email.com,+49-30-5550104,europe,germany,Yoga Mat,3,25.00,0,75,2024/01/12,Delivered,Credit Card,Mike T.
4,1005,Emma Nguyen,emma.nguyen@email.com,61-2-5550105,Asia Pacific,australia,Skincare Set,2,45.00,15%,76.5,14-01-2024,Delivered,credit card,Rachel M.
5,1006,NaN,frank.rossi@email.com,+39-06-5550106,Europe,Italy,Olive Oil Pack,4,18.99,NaN,75.96,01/15/2024,Delivered,Bank Transfer,James R.
6,1007,Grace Kim,grace.kim@email.com,82-2-5550107,Asia pacific,South Korea,Smartwatch,1,199.99,20%,159.99,2024-01-18,Delivered,Credit Card,Rachel M.
7,1008,Hiro Tanaka,hiro.tanaka@email.com,+81-3-5550108,asia pacific,Japan,Business Strategy Set,5,12.99,0%,64.95,20/01/2024,Delivered,Paypal,Rachel M.
8,1009,Isabella Garcia,isabella.garcia@email.com,+34-91-5550109,Europe,Spain,LEGO Set,-1,79.99,10%,71.99,2024-01-22,Delivered,Credit Card,James R.
9,1010,James Wilson,james.wilson@email.com,1-555-0110,North America,USA,Laptop Stand,2,34.99,none,69.98,25-Jan-2024,Delivered,Debit Card,Mike T.
10,1011,Alice Johnson,alice.johnson@email.com,555-0101,North America,USA,Python Programming,1,39.99,0,39.99,02/02/2024,Delivered,Credit Card,Mike T.
11,1012,Karen Patel,karen.patel@email.com,91-22-5550111,Asia Pacific,india,Formal Shirt,3,29.99,5%,85.47,2024-02-04,Delivered,PAYPAL,Sarah K.
12,1013,Liam O Brien,liam.obrien@email.com,+353-1-5550112,Europe,ireland,Air Fryer,1,89.99,NaN,89.99,06-Feb-2024,Delivered,Credit Card,James R.
13,1014,Mei Zhang,mei.zhang@email.com,86-10-5550113,asia pacific,China,Hair Care Kit,2,35.00,10%,63,2024/02/08,delivered,Alipay,Rachel M.
14,1015,Noah Brown,noah.brown@email.com,1-555-0114,North America,USA,Running Shoes,1,120.00,0%,120,10-02-2024,Delivered,Credit Card,Mike T.
15,1016,Olivia Martinez,olivia.martinez@email.com,52-55-5550115,Latin America,Mexico,Protein Powder,2,49.99,NaN,99.98,2024-02-12,Delivered,Debit card,Sarah K.
16,1017,Pedro Alves,pedro.alves@email.com,55-11-5550116,latin america,Brazil,Bluetooth Speaker,1,59.99,15%,50.99,14/02/2024,Delivered,Credit Card,Sarah K.
17,1018,Quinn Adams,quinn.adams@email.com,+1-555-0117,North America,Canada,Board Game,2,24.99,0,49.98,2024-02-16,DELIVERED,paypal,Mike T.
18,1019,Rita Singh,rita.singh@email.com,91-11-5550118,Asia Pacific,India,Saree,1,89.99,5%,85.49,18-Feb-2024,Delivered,UPI,Rachel M.
19,1020,Samuel Johnson,samuel.j@email.com,1-555-0119,north america,USA,Robot Vacuum,1,249.99,10%,224.99,2024-02-20,Delivered,credit card,Mike T.
20,1021,Tina Choi,tina.choi@email.com,82-2-5550120,Asia Pacific,south korea,Sheet Mask Pack,10,3.50,0,35,22/02/2024,Delivered,Credit Card,Rachel M.
21,1022,Clara Lee,CLARA.LEE@EMAIL.COM,(44) 20-5550103,Europe,UK,USB-C Hub,1,49.99,none,49.99,2024-02-24,Shipped,Debit Card,James R.
22,1023,Uma Sharma,uma.sharma@email.com,91-80-5550121,Asia Pacific,India,Data Science Guide,2,29.99,0%,59.98,01-Mar-2024,Delivered,Paypal,Rachel M.
23,1024,Victor Dupont,victor.dupont@email.com,33-1-5550122,europe,France,Wine Gift Set,1,75.00,NaN,75,03/03/2024,Delivered,Credit Card,James R.
24,1025,Wendy Hall,wendy.hall@email.com,1-555-0123,North America,USA,Dumbbell Set,1,89.99,10%,80.99,2024-03-05,Delivered,Credit Card,Mike T.
25,1026,Xander Liu,xander.liu@email.com,65-5550124,Asia Pacific,singapore,Gaming Mouse,1,69.99,5%,66.49,07-Mar-2024,Delivered,Paypal,Rachel M.
26,1027,Yara Al-Rashid,yara.rashid@email.com,971-4-5550125,middle east,UAE,Abaya,2,59.99,0,119.98,2024/03/09,Delivered,Credit Card,Sarah K.
27,1028,Zoe Thompson,zoe.thompson@email.com,61-3-5550126,Asia Pacific,Australia,Essential Oil Diffuser,1,39.99,NaN,39.99,11/03/2024,Delivered,Debit Card,Rachel M.
28,1029,Grace Kim,grace.kim@email.com,82-2-5550107,Asia pacific,South Korea,Sneakers,1,85.00,20%,68,2024-03-13,Delivered,credit card,Rachel M.
29,1030,Aaron White,aaron.white@email.com,1-555-0127,North America,USA,Webcam HD,2,44.99,0,89.98,15-Mar-2024,shipped,Credit Card,Mike T.
30,1031,Bella Rossi,bella.rossi@email.com,39-02-5550128,Europe,italy,Perfume,1,120.00,10%,108,17/03/2024,Delivered,Credit Card,James R.
31,1032,Carlos Mendez,carlos.m@email.com,52-33-5550129,Latin America,Mexico,Football,2,29.99,0%,59.98,2024-03-19,Delivered,debit card,Sarah K.
32,1033,Mei Zhang,mei.zhang@email.com,86-10-5550113,asia pacific,China,Power Bank,3,25.99,0,77.97,21-Mar-2024,Processing,Alipay,Rachel M.
33,1034,Diana Prince,diana.p@email.com,1-555-0130,North America,USA,Stand Mixer,1,299.99,15%,254.99,2024-03-22,Delivered,Credit Card,Mike T.
34,1035,Ethan Clark,ethan.clark@email.com,44-161-5550131,Europe,UK,Fiction Novel Pack,3,14.99,5%,42.72,24/03/2024,Delivered,Paypal,James R.
35,1036,Fatima Hassan,fatima.h@email.com,20-2-5550132,middle east,Egypt,Casual Dress,2,39.99,10%,71.98,2024-03-26,Shipped,Credit Card,Sarah K.
36,1037,James Wilson,james.wilson@email.com,1-555-0110,North America,USA,Noise-Cancel Earbuds,1,129.99,0,129.99,01-Apr-2024,Delivered,Debit Card,Mike T.
37,1038,Gabriela Lima,gabriela.l@email.com,55-21-5550133,Latin america,Brazil,Makeup Palette,1,55.00,0%,55,2024/04/03,Delivered,credit card,Sarah K.
38,1039,Henry Ford,henry.ford@email.com,1-555-0134,North America,USA,Bicycle Helmet,1,59.99,NaN,59.99,05-Apr-2024,Delivered,Credit Card,Mike T.
39,1040,Iris Nakamura,iris.n@email.com,81-6-5550135,Asia Pacific,Japan,Rice Cooker,1,79.99,5%,75.99,07/04/2024,Delivered,paypal,Rachel M.
40,1041,Jack Turner,jack.turner@email.com,1-555-0136,North America,Canada,Smart TV,1,699.99,10%,629.99,2024-04-09,Delivered,Credit Card,Mike T.
41,1042,Kira Svensson,kira.s@email.com,46-8-5550137,europe,Sweden,Denim Jeans,2,69.99,0,139.98,11-Apr-2024,Delivered,Debit Card,James R.
42,1043,Leo Fernandez,leo.f@email.com,34-93-5550138,Europe,Spain,Gourmet Chocolate Box,3,22.99,NaN,68.97,2024-04-13,Processing,Credit Card,James R.
43,1044,Olivia Martinez,olivia.martinez@email.com,52-55-5550115,Latin America,mexico,Blender,1,49.99,5%,47.49,15/04/2024,Delivered,Debit Card,Sarah K.
44,1045,Mia Hoffman,mia.h@email.com,49-89-5550139,Europe,Germany,Tennis Racket,1,89.99,10%,80.99,17-Apr-2024,Delivered,Paypal,James R.
45,1046,Nathan Brooks,nathan.b@email.com,1-555-0140,north america,USA,Self-Help Collection,4,19.99,0%,79.96,2024-04-19,Delivered,Credit Card,Mike T.
46,1047,Nour Al Amin,nour.amin@email.com,966-11-5550141,middle east,Saudi Arabia,Tablet,1,349.99,15%,297.49,21/04/2024,Shipped,credit card,Sarah K.
47,1048,Olivia Chen,olivia.chen@email.com,1-555-0142,North America,USA,Nail Art Kit,1,24.99,0,24.99,2024-04-22,delivered,Paypal,Mike T.
48,1049,Samuel Johnson,samuel.j@email.com,1-555-0119,North America,USA,Treadmill,1,799.99,5%,759.99,24-Apr-2024,Delivered,credit card,Mike T.
49,1050,Paula Costa,paula.c@email.com,351-21-5550143,europe,Portugal,Summer Dress,3,35.00,0%,105,26/04/2024,Delivered,Credit Card,James R.
50,1051,Aaron White,aaron.white@gmail.com,1-555-0127,North America,USA,Webcam HD,1,44.99,0,44.99,2024-04-28,Delivered,Credit Card,Mike T.
51,1052,NaN,bademail@@domain,NaN,NaN,NaN,Unknown Product,0,NaN,-,-,2024-04-30,Pending,NaN,NaN
52,1053,Samuel Johnson,samuel.j@email.com,1-555-0119,North America,United States,Robot Vacuum,1,249.99,10%,224.99,2024-02-20,Delivered,Credit Card,Mike T.
53,1054,james wilson,james.wilson@email.com,555-0110,north america,usa,Laptop Stand,2,34.99,0,69.98,2024-01-25,delivered,debit card,mike t.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       54 non-null     int64
 1   Customer Name  52 non-null     object
 2   email          54 non-null     object
 3   Phone Number   53 non-null     object
 4   Region         53 non-null     object
 5   country        53 non-null     object
 6   Product        54 non-null     object
 7   Qty            54 non-null     int64
 8   unit price     53 non-null     float64
 9   Discount       46 non-null     object
 10  Total          54 non-null     object
 11  Order Date     54 non-null     object
 12  Status         54 non-null     object
 13  payment        53 non-null     object
 14  Sales_Rep      53 non-null     object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.5+ KB

In [5]:
df.describe()

          Order_ID        Qty  unit price
count    54.000000  54.000000   53.000000
mean   1027.500000   1.759259  101.963585
std      15.732133   1.541075  148.594879
min    1001.000000  -1.000000    3.500000
25%    1014.250000   1.000000   34.990000
50%    1027.500000   1.000000   55.000000
75%    1040.750000   2.000000   89.990000
max    1054.000000  10.000000  799.990000

In [6]:
df.describe().round()

       Order_ID   Qty  unit price
count      54.0  54.0        53.0
mean     1028.0   2.0       102.0
std        16.0   2.0       149.0
min      1001.0  -1.0         4.0
25%      1014.0   1.0        35.0
50%      1028.0   1.0        55.0
75%      1041.0   2.0        90.0
max      1054.0  10.0       800.0

In [7]:
df.isnull().sum()

Order_ID         0
Customer Name    2
email            0
Phone Number     1
Region           1
country          1
Product          0
Qty              0
unit price       1
Discount         8
Total            0
Order Date       0
Status           0
payment          1
Sales_Rep        1
dtype: int64

In [8]:
df.shape

(54, 15)

In [9]:
df.isnull().sum()/len(df)*100

Order_ID          0.000000
Customer Name     3.703704
email             0.000000
Phone Number      1.851852
Region            1.851852
country           1.851852
Product           0.000000
Qty               0.000000
unit price        1.851852
Discount         14.814815
Total             0.000000
Order Date        0.000000
Status            0.000000
payment           1.851852
Sales_Rep         1.851852
dtype: float64

In [10]:
df[df.duplicated()].shape

(0, 15)

In [11]:
df[df.duplicated()]

Empty DataFrame
Columns: [Order_ID, Customer Name, email, Phone Number, Region, country, Product, Qty, unit price, Discount, Total, Order Date, Status, payment, Sales_Rep]
Index: []

In [12]:
df['Order_ID'].value_counts()

Order_ID
1001    1
1041    1
1030    1
1031    1
1032    1
1033    1
1034    1
1035    1
1036    1
1037    1
1038    1
1039    1
1040    1
1042    1
1002    1
1043    1
1044    1
1045    1
1046    1
1047    1
1048    1
1049    1
1050    1
1051    1
1052    1
1053    1
1029    1
1028    1
1027    1
1026    1
1003    1
1004    1
1005    1
1006    1
1007    1
1008    1
1009    1
1010    1
1011    1
1012    1
1013    1
1014    1
1015    1
1016    1
1017    1
1018    1
1019    1
1020    1
1021    1
1022    1
1023    1
1024    1
1025    1
1054    1
Name: count, dtype: int64

In [13]:
df['Order_ID'].value_counts().head(10)

Order_ID
1001    1
1041    1
1030    1
1031    1
1032    1
1033    1
1034    1
1035    1
1036    1
1037    1
Name: count, dtype: int64

In [16]:
for col in df.columns:
    if df[col].nunique()<20:
        print(df[col].value_counts())
        print('-'*50)

Region
North America    15
Europe            9
Asia Pacific      8
north america     4
europe            4
asia pacific      3
Latin America     3
middle east       3
Asia pacific      2
latin america     1
Latin america     1
Name: count, dtype: int64
--------------------------------------------------
Qty
 1     29
 2     13
 3      6
 4      2
 5      1
-1      1
 10     1
 0      1
Name: count, dtype: int64
--------------------------------------------------
Discount
0       12
10%     10
5%       8
0%       7
15%      4
20%      2
none     2
-        1
Name: count, dtype: int64
--------------------------------------------------
Status
Delivered     41
delivered      4
Shipped        3
DELIVERED      2
Processing     2
shipped        1
Pending        1
Name: count, dtype: int64
--------------------------------------------------
payment
Credit Card      23
Debit Card        7
credit card       6
Paypal            6
paypal            3
Alipay            2
debit card        2
Bank Transfer     1
PAYPAL            1
Debit card        1
UPI               1
Name: count, dtype: int64
--------------------------------------------------
Sales_Rep
Mike T.      18
James R.     12
Rachel M.    12
Sarah K.     10
mike t.       1
Name: count, dtype: int64
--------------------------------------------------

In [18]:
df['unit price'].unique()

array([ 89.99, 149.99,  59.99,  25.  ,  45.  ,  18.99, 199.99,  12.99,
        79.99,  34.99,  39.99,  29.99,  35.  , 120.  ,  49.99,  24.99,
       249.99,   3.5 ,  75.  ,  69.99,  85.  ,  44.99,  25.99, 299.99,
        14.99, 129.99,  55.  , 699.99,  22.99,  19.99, 349.99, 799.99,
          nan])

In [19]:
df_price=df[df['unit price'] != 'nan']['unit price']

In [20]:
price_median=df_price.dropna().median()

In [21]:
price_median

55.0

In [27]:
#df.replace('nan',price_median,inplace=True)
df.fillna(price_median,inplace=True)

In [30]:
df['unit price'].unique()

array([ 89.99, 149.99,  59.99,  25.  ,  45.  ,  18.99, 199.99,  12.99,
        79.99,  34.99,  39.99,  29.99,  35.  , 120.  ,  49.99,  24.99,
       249.99,   3.5 ,  75.  ,  69.99,  85.  ,  44.99,  25.99, 299.99,
        14.99, 129.99,  55.  , 699.99,  22.99,  19.99, 349.99, 799.99])

In [33]:
df.isnull().sum()

Order_ID         0
Customer Name    0
email            0
Phone Number     0
Region           0
country          0
Product          0
Qty              0
unit price       0
Discount         0
Total            0
Order Date       0
Status           0
payment          0
Sales_Rep        0
dtype: int64

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       54 non-null     int64
 1   Customer Name  54 non-null     object
 2   email          54 non-null     object
 3   Phone Number   54 non-null     object
 4   Region         54 non-null     object
 5   country        54 non-null     object
 6   Product        54 non-null     object
 7   Qty            54 non-null     int64
 8   unit price     54 non-null     float64
 9   Discount       54 non-null     object
 10  Total          54 non-null     object
 11  Order Date     54 non-null     object
 12  Status         54 non-null     object
 13  payment        54 non-null     object
 14  Sales_Rep      54 non-null     object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.5+ KB

In [35]:
df.head(10)

,Order_ID,Customer Name,email,Phone Number,Region,country,Product,Qty,unit price,Discount,Total,Order Date,Status,payment,Sales_Rep
0,1001,Alice Johnson,alice.johnson@email.com,555-0101,North America,USA,Wireless Headphones,2,89.99,10%,161.98,01/05/2024,Delivered,Credit Card,Mike T.
1,1002,BOB SMITH,bob.smith@email.com,+1-555-0102,north america,Canada,Winter Jacket,1,149.99,55.0,149.99,2024-01-07,delivered,paypal,Sarah K.
2,1003,Clara Lee,CLARA.LEE@EMAIL.COM,(44) 20-5550103,Europe,UK,Coffee Maker,1,59.99,5%,57.00,10-Jan-2024,DELIVERED,Debit Card,James R.
3,1004,david muller,david.muller@email.com,+49-30-5550104,europe,germany,Yoga Mat,3,25.00,0,75,2024/01/12,Delivered,Credit Card,Mike T.
4,1005,Emma Nguyen,emma.nguyen@email.com,61-2-5550105,Asia Pacific,australia,Skincare Set,2,45.00,15%,76.5,14-01-2024,Delivered,credit card,Rachel M.
5,1006,55.0,frank.rossi@email.com,+39-06-5550106,Europe,Italy,Olive Oil Pack,4,18.99,55.0,75.96,01/15/2024,Delivered,Bank Transfer,James R.
6,1007,Grace Kim,grace.kim@email.com,82-2-5550107,Asia pacific,South Korea,Smartwatch,1,199.99,20%,159.99,2024-01-18,Delivered,Credit Card,Rachel M.
7,1008,Hiro Tanaka,hiro.tanaka@email.com,+81-3-5550108,asia pacific,Japan,Business Strategy Set,5,12.99,0%,64.95,20/01/2024,Delivered,Paypal,Rachel M.
8,1009,Isabella Garcia,isabella.garcia@email.com,+34-91-5550109,Europe,Spain,LEGO Set,-1,79.99,10%,71.99,2024-01-22,Delivered,Credit Card,James R.
9,1010,James Wilson,james.wilson@email.com,1-555-0110,North America,USA,Laptop Stand,2,34.99,none,69.98,25-Jan-2024,Delivered,Debit Card,Mike T.

In [36]:
df=pd.read_csv('D:/90 days AI Ml/Day 10 pandas/messy_sales_data.csv')

In [37]:
df

,Order_ID,Customer Name,email,Phone Number,Region,country,Product,Qty,unit price,Discount,Total,Order Date,Status,payment,Sales_Rep
0,1001,Alice Johnson,alice.johnson@email.com,555-0101,North America,USA,Wireless Headphones,2,89.99,10%,161.98,01/05/2024,Delivered,Credit Card,Mike T.
1,1002,BOB SMITH,bob.smith@email.com,+1-555-0102,north america,Canada,Winter Jacket,1,149.99,NaN,149.99,2024-01-07,delivered,paypal,Sarah K.
2,1003,Clara Lee,CLARA.LEE@EMAIL.COM,(44) 20-5550103,Europe,UK,Coffee Maker,1,59.99,5%,57.00,10-Jan-2024,DELIVERED,Debit Card,James R.
3,1004,david muller,david.muller@email.com,+49-30-5550104,europe,germany,Yoga Mat,3,25.00,0,75,2024/01/12,Delivered,Credit Card,Mike T.
4,1005,Emma Nguyen,emma.nguyen@email.com,61-2-5550105,Asia Pacific,australia,Skincare Set,2,45.00,15%,76.5,14-01-2024,Delivered,credit card,Rachel M.
5,1006,NaN,frank.rossi@email.com,+39-06-5550106,Europe,Italy,Olive Oil Pack,4,18.99,NaN,75.96,01/15/2024,Delivered,Bank Transfer,James R.
6,1007,Grace Kim,grace.kim@email.com,82-2-5550107,Asia pacific,South Korea,Smartwatch,1,199.99,20%,159.99,2024-01-18,Delivered,Credit Card,Rachel M.
7,1008,Hiro Tanaka,hiro.tanaka@email.com,+81-3-5550108,asia pacific,Japan,Business Strategy Set,5,12.99,0%,64.95,20/01/2024,Delivered,Paypal,Rachel M.
8,1009,Isabella Garcia,isabella.garcia@email.com,+34-91-5550109,Europe,Spain,LEGO Set,-1,79.99,10%,71.99,2024-01-22,Delivered,Credit Card,James R.
9,1010,James Wilson,james.wilson@email.com,1-555-0110,North America,USA,Laptop Stand,2,34.99,none,69.98,25-Jan-2024,Delivered,Debit Card,Mike T.
10,1011,Alice Johnson,alice.johnson@email.com,555-0101,North America,USA,Python Programming,1,39.99,0,39.99,02/02/2024,Delivered,Credit Card,Mike T.
11,1012,Karen Patel,karen.patel@email.com,91-22-5550111,Asia Pacific,india,Formal Shirt,3,29.99,5%,85.47,2024-02-04,Delivered,PAYPAL,Sarah K.
12,1013,Liam O Brien,liam.obrien@email.com,+353-1-5550112,Europe,ireland,Air Fryer,1,89.99,NaN,89.99,06-Feb-2024,Delivered,Credit Card,James R.
13,1014,Mei Zhang,mei.zhang@email.com,86-10-5550113,asia pacific,China,Hair Care Kit,2,35.00,10%,63,2024/02/08,delivered,Alipay,Rachel M.
14,1015,Noah Brown,noah.brown@email.com,1-555-0114,North America,USA,Running Shoes,1,120.00,0%,120,10-02-2024,Delivered,Credit Card,Mike T.
15,1016,Olivia Martinez,olivia.martinez@email.com,52-55-5550115,Latin America,Mexico,Protein Powder,2,49.99,NaN,99.98,2024-02-12,Delivered,Debit card,Sarah K.
16,1017,Pedro Alves,pedro.alves@email.com,55-11-5550116,latin america,Brazil,Bluetooth Speaker,1,59.99,15%,50.99,14/02/2024,Delivered,Credit Card,Sarah K.
17,1018,Quinn Adams,quinn.adams@email.com,+1-555-0117,North America,Canada,Board Game,2,24.99,0,49.98,2024-02-16,DELIVERED,paypal,Mike T.
18,1019,Rita Singh,rita.singh@email.com,91-11-5550118,Asia Pacific,India,Saree,1,89.99,5%,85.49,18-Feb-2024,Delivered,UPI,Rachel M.
19,1020,Samuel Johnson,samuel.j@email.com,1-555-0119,north america,USA,Robot Vacuum,1,249.99,10%,224.99,2024-02-20,Delivered,credit card,Mike T.
20,1021,Tina Choi,tina.choi@email.com,82-2-5550120,Asia Pacific,south korea,Sheet Mask Pack,10,3.50,0,35,22/02/2024,Delivered,Credit Card,Rachel M.
21,1022,Clara Lee,CLARA.LEE@EMAIL.COM,(44) 20-5550103,Europe,UK,USB-C Hub,1,49.99,none,49.99,2024-02-24,Shipped,Debit Card,James R.
22,1023,Uma Sharma,uma.sharma@email.com,91-80-5550121,Asia Pacific,India,Data Science Guide,2,29.99,0%,59.98,01-Mar-2024,Delivered,Paypal,Rachel M.
23,1024,Victor Dupont,victor.dupont@email.com,33-1-5550122,europe,France,Wine Gift Set,1,75.00,NaN,75,03/03/2024,Delivered,Credit Card,James R.
24,1025,Wendy Hall,wendy.hall@email.com,1-555-0123,North America,USA,Dumbbell Set,1,89.99,10%,80.99,2024-03-05,Delivered,Credit Card,Mike T.
25,1026,Xander Liu,xander.liu@email.com,65-5550124,Asia Pacific,singapore,Gaming Mouse,1,69.99,5%,66.49,07-Mar-2024,Delivered,Paypal,Rachel M.
26,1027,Yara Al-Rashid,yara.rashid@email.com,971-4-5550125,middle east,UAE,Abaya,2,59.99,0,119.98,2024/03/09,Delivered,Credit Card,Sarah K.
27,1028,Zoe Thompson,zoe.thompson@email.com,61-3-5550126,Asia Pacific,Australia,Essential Oil Diffuser,1,39.99,NaN,39.99,11/03/2024,Delivered,Debit Card,Rachel M.
28,1029,Grace Kim,grace.kim@email.com,82-2-5550107,Asia pacific,South Korea,Sneakers,1,85.00,20%,68,2024-03-13,Delivered,credit card,Rachel M.
29,1030,Aaron White,aaron.white@email.com,1-555-0127,North America,USA,Webcam HD,2,44.99,0,89.98,15-Mar-2024,shipped,Credit Card,Mike T.
30,1031,Bella Rossi,bella.rossi@email.com,39-02-5550128,Europe,italy,Perfume,1,120.00,10%,108,17/03/2024,Delivered,Credit Card,James R.
31,1032,Carlos Mendez,carlos.m@email.com,52-33-5550129,Latin America,Mexico,Football,2,29.99,0%,59.98,2024-03-19,Delivered,debit card,Sarah K.
32,1033,Mei Zhang,mei.zhang@email.com,86-10-5550113,asia pacific,China,Power Bank,3,25.99,0,77.97,21-Mar-2024,Processing,Alipay,Rachel M.
33,1034,Diana Prince,diana.p@email.com,1-555-0130,North America,USA,Stand Mixer,1,299.99,15%,254.99,2024-03-22,Delivered,Credit Card,Mike T.
34,1035,Ethan Clark,ethan.clark@email.com,44-161-5550131,Europe,UK,Fiction Novel Pack,3,14.99,5%,42.72,24/03/2024,Delivered,Paypal,James R.
35,1036,Fatima Hassan,fatima.h@email.com,20-2-5550132,middle east,Egypt,Casual Dress,2,39.99,10%,71.98,2024-03-26,Shipped,Credit Card,Sarah K.
36,1037,James Wilson,james.wilson@email.com,1-555-0110,North America,USA,Noise-Cancel Earbuds,1,129.99,0,129.99,01-Apr-2024,Delivered,Debit Card,Mike T.
37,1038,Gabriela Lima,gabriela.l@email.com,55-21-5550133,Latin america,Brazil,Makeup Palette,1,55.00,0%,55,2024/04/03,Delivered,credit card,Sarah K.
38,1039,Henry Ford,henry.ford@email.com,1-555-0134,North America,USA,Bicycle Helmet,1,59.99,NaN,59.99,05-Apr-2024,Delivered,Credit Card,Mike T.
39,1040,Iris Nakamura,iris.n@email.com,81-6-5550135,Asia Pacific,Japan,Rice Cooker,1,79.99,5%,75.99,07/04/2024,Delivered,paypal,Rachel M.
40,1041,Jack Turner,jack.turner@email.com,1-555-0136,North America,Canada,Smart TV,1,699.99,10%,629.99,2024-04-09,Delivered,Credit Card,Mike T.
41,1042,Kira Svensson,kira.s@email.com,46-8-5550137,europe,Sweden,Denim Jeans,2,69.99,0,139.98,11-Apr-2024,Delivered,Debit Card,James R.
42,1043,Leo Fernandez,leo.f@email.com,34-93-5550138,Europe,Spain,Gourmet Chocolate Box,3,22.99,NaN,68.97,2024-04-13,Processing,Credit Card,James R.
43,1044,Olivia Martinez,olivia.martinez@email.com,52-55-5550115,Latin America,mexico,Blender,1,49.99,5%,47.49,15/04/2024,Delivered,Debit Card,Sarah K.
44,1045,Mia Hoffman,mia.h@email.com,49-89-5550139,Europe,Germany,Tennis Racket,1,89.99,10%,80.99,17-Apr-2024,Delivered,Paypal,James R.
45,1046,Nathan Brooks,nathan.b@email.com,1-555-0140,north america,USA,Self-Help Collection,4,19.99,0%,79.96,2024-04-19,Delivered,Credit Card,Mike T.
46,1047,Nour Al Amin,nour.amin@email.com,966-11-5550141,middle east,Saudi Arabia,Tablet,1,349.99,15%,297.49,21/04/2024,Shipped,credit card,Sarah K.
47,1048,Olivia Chen,olivia.chen@email.com,1-555-0142,North America,USA,Nail Art Kit,1,24.99,0,24.99,2024-04-22,delivered,Paypal,Mike T.
48,1049,Samuel Johnson,samuel.j@email.com,1-555-0119,North America,USA,Treadmill,1,799.99,5%,759.99,24-Apr-2024,Delivered,credit card,Mike T.
49,1050,Paula Costa,paula.c@email.com,351-21-5550143,europe,Portugal,Summer Dress,3,35.00,0%,105,26/04/2024,Delivered,Credit Card,James R.
50,1051,Aaron White,aaron.white@gmail.com,1-555-0127,North America,USA,Webcam HD,1,44.99,0,44.99,2024-04-28,Delivered,Credit Card,Mike T.
51,1052,NaN,bademail@@domain,NaN,NaN,NaN,Unknown Product,0,NaN,-,-,2024-04-30,Pending,NaN,NaN
52,1053,Samuel Johnson,samuel.j@email.com,1-555-0119,North America,United States,Robot Vacuum,1,249.99,10%,224.99,2024-02-20,Delivered,Credit Card,Mike T.
53,1054,james wilson,james.wilson@email.com,555-0110,north america,usa,Laptop Stand,2,34.99,0,69.98,2024-01-25,delivered,debit card,mike t.

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       54 non-null     int64
 1   Customer Name  52 non-null     object
 2   email          54 non-null     object
 3   Phone Number   53 non-null     object
 4   Region         53 non-null     object
 5   country        53 non-null     object
 6   Product        54 non-null     object
 7   Qty            54 non-null     int64
 8   unit price     53 non-null     float64
 9   Discount       46 non-null     object
 10  Total          54 non-null     object
 11  Order Date     54 non-null     object
 12  Status         54 non-null     object
 13  payment        53 non-null     object
 14  Sales_Rep      53 non-null     object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.5+ KB

In [39]:
df.isnull().sum()

Order_ID         0
Customer Name    2
email            0
Phone Number     1
Region           1
country          1
Product          0
Qty              0
unit price       1
Discount         8
Total            0
Order Date       0
Status           0
payment          1
Sales_Rep        1
dtype: int64

In [41]:
df['unit price'].unique()

array([ 89.99, 149.99,  59.99,  25.  ,  45.  ,  18.99, 199.99,  12.99,
        79.99,  34.99,  39.99,  29.99,  35.  , 120.  ,  49.99,  24.99,
       249.99,   3.5 ,  75.  ,  69.99,  85.  ,  44.99,  25.99, 299.99,
        14.99, 129.99,  55.  , 699.99,  22.99,  19.99, 349.99, 799.99,
          nan])

In [45]:
df['unit price'].fillna(df['unit price'].median(),inplace=True)

C:\Users\AKASH\AppData\Local\Temp\ipykernel_8476\1578944718.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['unit price'].fillna(df['unit price'].median(),inplace=True)